# Generated by Django 5.1.3 on 2025-01-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='price',
            field=models.CharField(default='الاتفاق عبر الهاتف', max_length=255),
        ),
    ]
