# Generated by Django 5.1.3 on 2024-12-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_posts_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
