# Generated by Django 5.1.3 on 2024-12-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_userprofile_address_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='workAs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
