# Generated by Django 5.1.3 on 2024-12-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_userprofile_workas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companyId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='CompanyId', to=settings.AUTH_USER_MODEL),
        ),
    ]
