# Generated by Django 5.1.3 on 2024-12-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_alter_userprofile_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('worker', 'Worker'), ('company', 'Company')], default='homeowner', max_length=10),
        ),
    ]
