# Generated by Django 4.2.17 on 2025-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0010_workerinvitation_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(default="palestine", max_length=255),
        ),
    ]
