# Generated by Django 4.2.17 on 2025-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0011_alter_userprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="price",
            field=models.CharField(default="الاتفاق عبر الهاتف", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
