# Generated by Django 4.2.17 on 2025-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0013_posts_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UsersCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
            ],
        ),
    ]
