# Generated by Django 4.2.17 on 2025-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0014_citycategory_userscategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
            ],
        ),
    ]
