# Generated by Django 4.2.17 on 2025-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0016_posts_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="post_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posts",
            name="post_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
