# Generated by Django 4.2.17 on 2025-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0017_posts_post_date_posts_post_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="scheduled_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
