# Generated by Django 4.2.17 on 2025-01-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0018_posts_scheduled_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_users", to="prof.postscategory"
            ),
        ),
    ]
