# Generated by Django 4.2.17 on 2025-01-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0019_userprofile_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The average rating for this user",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rating_sum",
            field=models.PositiveIntegerField(
                default=0, help_text="The sum of all rating values given to this user"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_ratings",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The total number of ratings this user has received",
            ),
        ),
    ]
