# Generated by Django 4.2.17 on 2025-01-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prof", "0020_userprofile_rating_userprofile_rating_sum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("done", "Done"),
                ],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
